variables:
  REGISTRY_PROJECT: cthulhoo
  FF_SCRIPT_SECTIONS: "true"
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fast
  CACHE_COMPRESSION_LEVEL: fast
  TRANSFER_METER_FREQUENCY: 5s

stages:
  - build

include:
  - project: 'ci/ci-templates'
    ref: master
    file: .ci-build-docker-kaniko.yml

build:
  stage: build
  image: registry.fakecake.org/docker.io/python:3.11-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - cp pip.conf /etc/pip.conf
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  cache:
    paths:
      - .cache

build-image:
  extends: .build-docker-kaniko
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    NAME: ${CI_PROJECT_NAME}
    VERSION: latest
  needs:
    - job: build
