FROM registry.fakecake.org/docker.io/python:3.11-alpine AS build

WORKDIR /app

ADD requirements.txt /app
ADD pip.conf /etc/pip.conf

RUN pip3 install -r requirements.txt

ADD docs /app/docs
ADD mkdocs.yml /app/

RUN mkdocs build --strict

FROM registry.fakecake.org/docker.io/nginxinc/nginx-unprivileged:1-alpine

COPY --from=build /app/public /usr/share/nginx/html
COPY redirects.conf /etc/nginx/conf.d/
