site_name: Tiny Tiny RSS
site_url: https://tt-rss.org
site_dir: public
markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
plugins:
  - search
  - glightbox
extra_css:
  - stylesheets/extra.css
theme:
  logo: https://tt-rss.org/images/icon_classic_128.png
  favicon: https://tt-rss.org/favicon.ico
  plugins:
    - optimize
  features:
    - navigation.tabs
    - content.code.copy
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
